apiVersion: apps/v1beta2
kind: Service
metadata:
  name: onlineshopping-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: onlineshopping-service
    role: onlineshoppingrole
